.gitignore
src/__tests__/Broker.test.tsx
src/components/Paginator.tsx
src/pages/Broker.tsx
src/pages/brokers/BrokerPage.tsx
src/pages/brokers/BrokersPage.tsx
src/pages/creditorInstitutions/CreditorInstitutions.tsx
src/util/routes.tsx

- implemented Brokers Table
- fix some eslint errors without `suppress`
To introduce new feature 
- manually
- jest

[PCFG-68] Brokers

---

.devops/azure-templates/make-build.yml
.devops/deploy-pipelines.yml

[PCFG-56] azure pipeline

---

.devops/azure-templates/make-build.yml
.devops/deploy-pipelines.yml
.env.dev
.env.local
.env.prod
.env.uat
.gitignore
env.sh
package.json
src/index.html
src/pages/brokers/BrokersPage.tsx
src/util/apiClient.tsx
src/util/config.ts

Generate dynamic env according to pipeline configuration
- removed env.<dev|uat|prod>
- generated env.config.js automatically
- fixed jest test to upload env configuration

[PCFG-89] env generation script

---

src/components/Sidebar.tsx
src/pages/brokers/BrokerPage.tsx

- implemented Broker Details page
To introduce new feature
- manually

[PCFG-69] broker

---

.devops/azure-templates/make-build.yml
.devops/deploy-pipelines.yml
.env.local.example
.gitignore
package.json
src/assets/styles/custom.scss
src/components/Layout.tsx
src/pages/icas/CheckICA.tsx
yarn.lock

Added XSD Schema validation
- upload XML
- fix lib version due to vulnerabilities

[PCFG-85] XSD Validation

---

.devops/code-review-pipelines.yml
.env.local
.gitignore
src/pages/brokers/BrokersPage.tsx
src/pages/brokers/CreateBrokerPage.tsx
src/util/routes.tsx

- Added `Create Broker Page`
To add a new feature
manually

[PCFG-70] Create Broker

---

.gitignore
src/pages/brokers/BrokersPage.tsx
src/pages/brokers/EditBrokerPage.tsx
src/util/routes.tsx

- Added `Edit Broker Page`
To add a new feature
manually

[PCFG-72] Edit Broker

---

src/__tests__/PaymentServiceProviders.test.tsx
src/assets/styles/custom.scss
src/authConfig.tsx
src/components/Sidebar.tsx
src/components/SidebarItems.tsx
src/pages/brokers/BrokerPage.tsx
src/pages/brokers/BrokersPage.tsx
src/pages/paymentServiceProviders/PaymentServiceProvider.tsx
src/pages/paymentServiceProviders/PaymentServiceProviders.tsx
src/util/routes.tsx

Added PSP list and details sections.
- refactoring sidebar in order to group domain info;
- added PSP list section;
- added PSP details section;
- minor fix about HTML on broker details section.

[PCFG-113] PSP sections

---

src/__tests__/BrokerPSP.test.tsx
src/components/Sidebar.tsx
src/components/SidebarItems.tsx
src/pages/brokers/BrokerPage.tsx
src/pages/brokers/BrokersPage.tsx
src/pages/brokersPSP/brokerPSP.tsx
src/pages/brokersPSP/brokersPSP.tsx
src/pages/paymentServiceProviders/PaymentServiceProviders.tsx
src/util/routes.tsx

Added broker PSP list and details
- added broker PSP list section;
- added broker PSP details section;
- fix sidebar navigation.

[PCFG-114] Brokers PSP

---

src/__tests__/Stations.test.tsx
src/components/Sidebar.tsx
src/components/SidebarItems.tsx
src/pages/stations/Station.tsx
src/pages/stations/Stations.tsx
src/util/routes.tsx

Added station list and details
- added station list section;
- added station details section.

[PCFG-115] Stations

---

src/__tests__/Channels.test.tsx
src/components/Sidebar.tsx
src/components/SidebarItems.tsx
src/pages/channels/Channel.tsx
src/pages/channels/Channels.tsx
src/util/routes.tsx

Added channel list and details
- added channel list section;
- added channel details section.

[PCFG-116] Channels

---

src/pages/brokers/BrokersPage.tsx
src/pages/brokersPSP/brokersPSP.tsx
src/pages/channels/Channel.tsx
src/pages/channels/Channels.tsx
src/pages/creditorInstitutions/CreditorInstitution.tsx

Fix some API responses.
Depends on #37 
- improvements regarding API responses

[PCFG-122] API responses refactoring

---

src/pages/creditorInstitutions/EditCreditorInstitution.tsx
src/pages/paymentServiceProviders/CreatePaymentServiceProvider.tsx
src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx
src/pages/paymentServiceProviders/PaymentServiceProvider.tsx
src/pages/paymentServiceProviders/PaymentServiceProviders.tsx
src/util/routes.tsx

Payment Service Provider (PSP) functionalities: creation, editing and removal
- view Channels in PSP details;
- create a PSP;
- edit a PSP;
- remove a PSP.

[PCFG-109] PSP C/U/D

---

src/pages/brokersPSP/BrokerPSP.tsx
src/pages/brokersPSP/BrokersPSP.tsx
src/pages/brokersPSP/CreateBrokerPSP.tsx
src/pages/brokersPSP/EditBrokerPSP.tsx
src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx
src/pages/paymentServiceProviders/PaymentServiceProvider.tsx
src/util/routes.tsx

Added creation, editing and removal functionalities of broker PSP.
- create a broker PSP
- edit a broker PSP
- remove a broker PSP

[PCFG-110] Broker PSP C/U/D

---

src/pages/channels/Channel.tsx
src/pages/channels/Channels.tsx
src/pages/channels/CreateChannel.tsx
src/pages/channels/EditChannel.tsx
src/util/routes.tsx
tsconfig.json

Added creation, editing and removal functionalities to channel section.
- create a channel;
- edit a channel;
- delete a channel

[PCFG-111] Channel C/U/D

---

src/pages/brokers/CreateBrokerPage.tsx
src/pages/brokers/EditBrokerPage.tsx
src/pages/brokersPSP/CreateBrokerPSP.tsx
src/pages/brokersPSP/EditBrokerPSP.tsx
src/pages/creditorInstitutions/CreateCreditorInstitution.tsx
src/pages/creditorInstitutions/EditCreditorInstitution.tsx
src/pages/paymentServiceProviders/CreatePaymentServiceProvider.tsx
src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx
src/pages/stations/CreateStation.tsx
src/pages/stations/EditStation.tsx
src/pages/stations/Station.tsx
src/pages/stations/Stations.tsx
src/util/routes.tsx

Added creation, editing and removal functionalities to station section.
- create a station;
- edit a station;
- remove a station.
-

[PCFG-108] Station C/U/D

---

src/components/Ordering.tsx
src/pages/brokers/BrokerPage.tsx
src/pages/brokers/BrokersPage.tsx
src/pages/brokers/EditBrokerPage.tsx
src/pages/brokersPSP/BrokerPSP.tsx
src/pages/brokersPSP/BrokersPSP.tsx
src/pages/brokersPSP/EditBrokerPSP.tsx
src/pages/channels/Channel.tsx
src/pages/channels/Channels.tsx
src/pages/channels/EditChannel.tsx
src/pages/creditorInstitutions/CreditorInstitutions.tsx
src/pages/paymentServiceProviders/PaymentServiceProviders.tsx
src/pages/stations/Stations.tsx

Depends on #49 
- Added asc/desc ordering option to all section

[PCFG-136] Ordering

---

src/__tests__/ConfigurationKeys.test.tsx
src/assets/styles/custom.scss
src/components/Ordering.tsx
src/components/Sidebar.tsx
src/components/SidebarItems.tsx
src/pages/configuration/ConfigurationKeys.tsx
src/util/routes.tsx

Section configuration keys
Depends on [BE PCFG-140](https://github.com/pagopa/pagopa-api-config/pull/70)
- list of configuration key
- create a configuration key
- edit a configuration key
- remove a configuration key

[PCFG-150] CRUD Configuration Keys

---

src/__tests__/Pdds.test.tsx
src/components/SidebarItems.tsx
src/pages/configuration/ConfigurationKeys.tsx
src/pages/configuration/Pdds.tsx
src/util/routes.tsx

Section PDD
Depends on #53 
- list of pdd configuration
- create a pdd configuration
- edit a pdd configuration
- remove a pdd configuration

[PCFG-151] CRUD PDD

---

package.json
yarn.lock

According to dependabot issues, the PR applies lib resolutions to specific version.

Lib resolutions

---

src/assets/styles/custom.scss
src/components/SidebarItems.tsx
src/pages/icas/ICAs.tsx
src/util/routes.tsx

Depends on [swagger fix](https://github.com/pagopa/pagopa-api-config/pull/80)
- view ICA list
- upload ICA configuration
- download ICA configuration
- delete ICA configuration

[PCFG-146] ICA section

---

src/__tests__/CDIs.test.tsx
src/assets/styles/custom.scss
src/components/SidebarItems.tsx
src/pages/cdis/CDIs.tsx
src/pages/icas/ICAs.tsx
src/util/routes.tsx

Depends on #57 
- view CDI list
- upload CDI configuration
- download CDI configuration
- delete CDI configuration

[PCFG-148] CDI section

---

src/__tests__/CounterpartTables.test.tsx
src/assets/styles/custom.scss
src/components/SidebarItems.tsx
src/pages/counterparttables/CounterpartTables.tsx
src/util/routes.tsx

- view Counterpart Table list
- upload Counterpart Table configuration
- download Counterpart Table configuration
- delete Counterpart Table configuration

[PCFG-147] Counterpart Tables section

---

src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx

Depends on https://github.com/pagopa/pagopa-api-config/pull/85
- create psp-channel relationship
- edit payment types for a psp-channel tuple 
- remove psp-channel relationship

[PCFG-169] PSP-Channel relationship

---

.github/workflows/main.yml
src/pages/stations/CreateStation.tsx
src/pages/stations/EditStation.tsx
src/pages/stations/Station.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/87
- added POF service to station 
- added github action

[PCFG-177] POF Service

---

src/pages/creditorInstitutions/CreditorInstitution.tsx

[PCFG-191] fix aux digit

---

src/pages/brokers/BrokersPage.tsx
src/pages/brokers/EditBrokerPage.tsx
src/pages/brokersPSP/BrokersPSP.tsx
src/pages/brokersPSP/EditBrokerPSP.tsx
src/pages/cdis/CDIs.tsx
src/pages/channels/EditChannel.tsx
src/pages/counterparttables/CounterpartTables.tsx
src/pages/creditorInstitutions/EditCreditorInstitution.tsx
src/pages/icas/CheckICA.tsx
src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx
src/pages/stations/EditStation.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/88
- fix undo bugs

[PCFG-181] Fix undo

---

src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/90

[PCFG-187] Added details in Error Popup

---

src/pages/creditorInstitutions/EditCreditorInstitution.tsx

[PCFG-183] Bug Fix Button "Nuovo"

---

src/pages/creditorInstitutions/EditCreditorInstitution.tsx

- add encoding from EC edit section

[PCFG-201] Encoding

---

package.json
src/assets/styles/custom.scss
src/pages/creditorInstitutions/EditCreditorInstitution.tsx
yarn.lock

- C/U/D ec-station relationship

[PCFG-202] EC-Station relationship

---

src/pages/stations/Station.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/93
- View creditor institution list in station section

[PCFG-172] Creditor institution list in station section

---

src/__tests__/MassiveLoading.test.tsx
src/assets/styles/custom.scss
src/components/Sidebar.tsx
src/components/SidebarItems.tsx
src/pages/massiveloading/MassiveLoading.tsx
src/util/routes.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/94
[Here](https://github.com/pagopa/pagopa-api-config/blob/main/src/test/resources/file/ci_station_ok.csv) can be found an example of CSV file.
- creditor institution-station relationship massive loading

[PCFG-170] Massive loading

---

src/pages/creditorInstitutions/CreditorInstitution.tsx
src/pages/stations/Station.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/95
- show more info about creditor institution-station details
- minor fix about encoding of creditor institution

[PCFG-206] Creditor institution - station details

---

src/pages/stations/Station.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/97
Added a button to export a CSV file with relation info EC-Station
to add a new feature. See the [task Jira](https://pagopa.atlassian.net/browse/PCFG-171)
- manually

[PCFG-171] Export CSV Station-EC

---

src/components/Sidebar.tsx
src/components/SidebarItems.tsx
src/pages/batchoperations/MassiveLoading.tsx
src/pages/batchoperations/MassiveMigration.tsx
src/util/routes.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/100
- Massive migration feature

[PCFG-284] Massive migration

---

.github/auto_assign.yml
.github/workflows/assignee.yml
.github/workflows/deploy.yml
.pre-commit-config.yaml

[PPD-185] Strategia rilasci

---

src/components/CITableModal.tsx
src/components/ConfirmationModal.tsx
src/components/Filters.tsx
src/pages/brokers/BrokersPage.tsx
src/pages/brokersPSP/BrokersPSP.tsx
src/pages/cdis/CDIs.tsx
src/pages/channels/Channels.tsx
src/pages/configuration/ConfigurationKeys.tsx
src/pages/configuration/PaymentType.tsx
src/pages/configuration/Pdds.tsx
src/pages/configuration/WFESPPlugins.tsx
src/pages/counterparttables/CounterpartTables.tsx
src/pages/creditorInstitutions/CreditorInstitutions.tsx
src/pages/icas/ICAs.tsx
src/pages/paymentServiceProviders/PaymentServiceProviders.tsx
src/pages/stations/Stations.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/118
- find creditor institutions having a specified IBAN (`equals`)

[PCFG-214] Find creditor institutions by IBAN 

---

.devops/azure-templates/node-versioning.yml
.devops/deploy-pipelines.yml

-  [x] Bug fix (non-breaking change which fixes an issue)

Fix Deploy Pipeline

---

src/pages/creditorInstitutions/CreditorInstitutions.tsx

- added an info toast when searching IBAN

Cosmetic fix

---

src/pages/channels/Channel.tsx
src/pages/paymentServiceProviders/PaymentServiceProvider.tsx

Added PSP section in Channel Page
[Jira task](https://pagopa.atlassian.net/browse/PCFG-223)
manually

[PCFG-223] PSP Section in Channel Page

---

.github/workflows/deploy.yml
src/pages/channels/Channel.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/122
to download a CSV file with PSP list of a channel
[Jira Task](https://pagopa.atlassian.net/browse/PCFG-200)

[PCFG-200] Export CSV PSP list

---

src/pages/channels/Channel.tsx
src/pages/channels/EditChannel.tsx

fix "new" button for adding a new payment type to a channel

[PCFG-238] fix payment type in Channel Page

---

src/pages/channels/Channel.tsx
src/pages/creditorInstitutions/CreditorInstitution.tsx
src/pages/paymentServiceProviders/PaymentServiceProvider.tsx

[PCFG-242] Fix checkbox

---

src/components/Sidebar.tsx

Fix css style regarding `/icas/check` menu item when selected.

[PCFG-245] Fix menu item

---

src/pages/channels/CreateChannel.tsx
src/pages/channels/EditChannel.tsx
src/pages/configuration/Pdds.tsx
src/pages/creditorInstitutions/EditCreditorInstitution.tsx
src/pages/icas/CheckICA.tsx
src/pages/stations/CreateStation.tsx
src/pages/stations/EditStation.tsx

Added default value and number type for input.

[PCFG-247] Input type check

---

src/pages/channels/CreateChannel.tsx
src/pages/channels/EditChannel.tsx

WFESP Plugin is now  a select.
The options are retrieved from BE
To improve UX

[PCFG-244] WFESP Plugin

---

src/pages/creditorInstitutions/EditCreditorInstitution.tsx

removed the possibility to set BARCODE_GS1_128 (deprecated)
BARCODE_GS1_128 is deprecated

[PCFG-258] fix BARCODE_GS1_128

---

.github/workflows/check_metadata_pr.yml
src/assets/styles/custom.scss
src/pages/brokers/BrokerPage.tsx
src/pages/brokers/BrokersPage.tsx
src/pages/brokers/CreateBrokerPage.tsx
src/pages/brokers/EditBrokerPage.tsx
src/pages/brokersPSP/BrokersPSP.tsx
src/pages/brokersPSP/CreateBrokerPSP.tsx
src/pages/brokersPSP/EditBrokerPSP.tsx
src/pages/cdis/CDIs.tsx
src/pages/channels/Channels.tsx
src/pages/channels/CreateChannel.tsx
src/pages/channels/EditChannel.tsx
src/pages/configuration/ConfigurationKeys.tsx
src/pages/configuration/PaymentType.tsx
src/pages/configuration/Pdds.tsx
src/pages/configuration/WFESPPlugins.tsx
src/pages/counterparttables/CounterpartTables.tsx
src/pages/creditorInstitutions/CreateCreditorInstitution.tsx
src/pages/creditorInstitutions/CreditorInstitutions.tsx
src/pages/creditorInstitutions/EditCreditorInstitution.tsx
src/pages/icas/CheckICA.tsx
src/pages/icas/ICAs.tsx
src/pages/paymentServiceProviders/CreatePaymentServiceProvider.tsx
src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx
src/pages/paymentServiceProviders/PaymentServiceProviders.tsx
src/pages/stations/CreateStation.tsx
src/pages/stations/EditStation.tsx
src/pages/stations/Stations.tsx

- cast error toast messages in several sections
When an error is very long it is not visible properly.
The error is related to a [library problem](https://github.com/fkhadra/react-toastify/issues/112) without a real fix. 
For this reason, it is been adopted a workaround to set explicitly the width of the `div` containing the message. 
The problem occurs only with the message came from by an async call.

[PCFG-261] Toast size

---

src/pages/brokers/BrokersPage.tsx
src/pages/brokersPSP/BrokersPSP.tsx
src/pages/channels/Channels.tsx
src/pages/stations/Stations.tsx

depends on https://github.com/pagopa/pagopa-api-config-fe/pull/99

[PCFG-260] ordinamento liste domini ec e psp

---

src/pages/brokers/BrokersPage.tsx

Fix error regarding columns order

Fix column order

---

.devops/code-review-pipelines.yml
src/pages/creditorInstitutions/EditCreditorInstitution.tsx

The station field must not be editable

[PCFG-265] fix station version

---

src/pages/counterparttables/CounterpartTables.tsx

Update PAGAMENTO_PRESSO_PSP according to info contained in the couterpart table xml 👉 https://pagopa.atlassian.net/browse/PCFG-198

[PCFG-198] EC field update

---

src/pages/channels/CreateChannel.tsx
src/pages/channels/EditChannel.tsx
src/pages/configuration/Pdds.tsx
src/pages/creditorInstitutions/EditCreditorInstitution.tsx
src/pages/stations/CreateStation.tsx
src/pages/stations/EditStation.tsx

[PCFG-274] Check on numeric fields

---

src/pages/stations/CreateStation.tsx
src/pages/stations/EditStation.tsx
src/pages/stations/Station.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/136
- added field into view, create and edit of station section
- add new field to station section

[PCFG-286] Added invio_rt_istantaneo to Stations

---

src/pages/configuration/PaymentType.tsx
src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx

- UPPERCASE for Tipi Versamento
- improve channel search in PSP section
- id searchable
- multi select payment types
[Feedback Operation](https://pagopa.atlassian.net/browse/PCFG-271)

Revision Payment Options

---

src/pages/icas/CheckICA.tsx

- added check on format of validity date in Check ICA section

[PCFG-288] Add check on validity date format

---

src/components/SidebarItems.tsx
src/pages/cdis/CheckCDI.tsx
src/util/routes.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/141
- Upload CDI and syntax and semantic checks

[PCFG-217] Verify CDI

---

src/components/Sidebar.tsx

feat: cosmetic fix

---

src/pages/cdis/CheckCDI.tsx
src/pages/icas/CheckICA.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/148
- refactoring check ICA 
-

feat: [PCFG-301] Check ICA

---

src/pages/icas/ICAs.tsx

- added forced upload of an ICA file

[PCFG-298] Force Upload ICA

---

CODEOWNERS
src/pages/batchoperations/MassiveLoading.tsx
src/pages/batchoperations/MassiveMigration.tsx
src/pages/cdis/CDIs.tsx
src/pages/cdis/CheckCDI.tsx
src/pages/counterparttables/CounterpartTables.tsx
src/pages/icas/CheckICA.tsx

- reset `event.target.value` after load a file
- new codeowners
to solve a bug when you load a file with the same name of the previuos
manually

[PCFG-307] Bugfix upload file with same name

---

src/pages/channels/Channel.tsx
src/pages/channels/CreateChannel.tsx
src/pages/channels/EditChannel.tsx
src/pages/stations/Station.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/160
- added target fields to Channel section for creation, viewing and editing

feat: [PCFG-315] Target fields for Channel

---

convert.py
src/pages/channels/Channel.tsx
src/pages/channels/CreateChannel.tsx
src/pages/channels/EditChannel.tsx
src/pages/paymentServiceProviders/PaymentServiceProviders.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/162
- swagger manipulation before codegen
- cosmetic fix about target description in channels section

feat: [PCFG-327] Swagger fix

---

src/components/SidebarItems.tsx
src/pages/batchoperations/MassiveIcas.tsx
src/pages/channels/CreateChannel.tsx
src/pages/channels/EditChannel.tsx
src/pages/stations/CreateStation.tsx
src/pages/stations/EditStation.tsx
src/util/routes.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/157
- added massive icas verification section

feat: [PCFG-311] Massive ICAs verification

---

src/pages/batchoperations/MassiveIcas.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/164
- added massive upload ICAs

feat: [PAGOPA-277] ICA massive upload

---

src/pages/channels/Channels.tsx
src/pages/stations/Stations.tsx

- added download button to export csv regarding stations and channels

feat: [PAGOPA-111] download stations and channels csv

---

package.json
src/components/CIEncodingModal.tsx
src/pages/creditorInstitutions/CreditorInstitutions.tsx

- added a new filter by postal encoding
To introduce a new filter
- manually

[PAGOPA-609] Search by Postal Encoding

---

src/pages/batchoperations/MassiveIcas.tsx

- added warning about iban and qrcode

[PAGOPA-628] Fix massive ICA

---

src/pages/channels/Channel.tsx
src/pages/channels/ChannelView.tsx
src/pages/channels/Channels.tsx
src/pages/channels/CreateChannel.tsx
src/pages/channels/EditChannel.tsx
src/pages/channels/Services.tsx

Adding the clone button in the channels menu and general optimization of the code regarding he channels. 
This change was required in order to refactor the existing code and add another functionality.
The code has been tested manually with the h2 backend.

PAGOPA-635 code generalization for channels

---

src/pages/channels/ChannelView.tsx

Fixing primitive change when editing or creating a channel
This change was required for the correct functionality of the service
This has been tested locally

PAGOPA-718 minor fix to primitive version

---

src/pages/channels/ChannelView.tsx
src/pages/creditorInstitutions/EditCreditorInstitution.tsx

With this pull request a bug fix is applied on Channels and EC section. In detail, in Channel section the button 'Salva' for the addition of relation between Channel and Creditor Institution is fixed in order to lock the click after the API call. Same fix is applied for the button 'Salva' for the addition of relation between Channel and Payment type.
Also, is added a new functionality where the dropdown view in EC section for the addition of relation between Channel and Creditor Institution will not show the Channels already present in table.
- Added lock on button 'Salva' related to EC-Channel relation addition
- Added lock on button 'Salva' related to Channel-Payment Type relation addition
- Added hiding of existent Channels in dropdown view during EC-Channel relation association
These …

[PAGOPA-708] fix: Associazione multipla EC-canali e Canali-Tipo versamento

---

package.json
src/__tests__/RefreshConfiguration.test.tsx
src/components/SidebarItems.tsx
src/pages/configuration/RefreshConfig.tsx
src/util/routes.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/183
- New page `Refresh Configuration`
- New table with the list of refreshable configurations
- Refresh button
- Confirm window
To make it possible to refresh node configurations, that is, to trigger the loading and instances update in memory.
- manually

feat: Add refresh configurazione nodo PAGOPA-653

---

src/pages/Login.tsx

Added version in the login page

Version FE

---

src/pages/channels/ChannelView.tsx
src/pages/stations/StationView.tsx

[PAGOPA-813] Fix default value select

---

src/pages/channels/ChannelView.tsx
src/pages/stations/StationView.tsx

depends on https://github.com/pagopa/pagopa-api-config/pull/192
- added target pof to station
- added target and service nmp  to channel

[PAGOPA-790] Multiple target endpoint

---

src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx
src/pages/paymentServiceProviders/PaymentServiceProvider.tsx

Removing transfer field from psp page, both visualization and edit page. This field is deprecated and has been removed from the backend previously.
This change was necessary to align the changes applied to the backend with the front end of api-config regarding the removed fields
This removal has been tested manually using h2 profile
Before:
After:

feat: remove transfer field from psp PAGOPA-1062

---

src/pages/channels/Channels.tsx
src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx
src/pages/stations/Stations.tsx

[PAGOPA-1012] feat: Search stations and channels by broker description

---

src/pages/configuration/RefreshConfig.tsx

In this branch we removed the possibility of refreshing a single domain, maintaining only the global refresh.
These changes are required due to the linearity of the refreshes and of the overall application. 
This has been tested manually, using H2 profile for backend.

feat: remove refresh single instances PAGOPA-1052

---

convert.py
src/pages/creditorInstitutions/CreditorInstitution.tsx

Adding ad hoc rule to manage the null publication date, which in the db is null for the elements inside the view. 
This fix was needed to change the behavior of the fe towards the publication date in the null case. 
This has been tested manually, with H2 profile

fix: pub date null for iban in EC page PAGOPA-1149

---

package.json
src/components/Sidebar.tsx

[PAGOPA-1237] Login logout

---

package.json
src/components/Sidebar.tsx
src/pages/configuration/RefreshConfig.tsx

[PAGOPA-1053] versione configurazione

---

src/pages/channels/ChannelView.tsx
src/pages/stations/StationView.tsx

- This PR adds a lock to two fields: `channel_code` and `station_code`
- this lock can be unlocked with a click on the icon 🔒 
For security purpose
manually

[git-checkout--b-PAGOPA-1289] lock

---

src/pages/brokers/BrokersPage.tsx
src/pages/brokersPSP/BrokersPSP.tsx
src/pages/cdis/CDIs.tsx
src/pages/channels/Channels.tsx
src/pages/counterparttables/CounterpartTables.tsx
src/pages/creditorInstitutions/CreditorInstitutions.tsx
src/pages/icas/ICAs.tsx
src/pages/paymentServiceProviders/PaymentServiceProviders.tsx
src/pages/stations/Stations.tsx
src/pages/views/CreditorInstitutionsView.tsx
src/pages/views/PspView.tsx

Fixing the pageinfo structure to avoid build failure
This fix is needed to build correctly the application, in order to deploy it correctly
Tested manually

PAGOPA-1462 fixing pageInfo

---

src/pages/creditorInstitutions/CreateCreditorInstitution.tsx
src/pages/creditorInstitutions/CreditorInstitution.tsx
src/pages/creditorInstitutions/EditCreditorInstitution.tsx

Adding cbill field in ec pages 
This change is required to handle correctly the cbill field and its value
This has been tested manually with h2 backend

PAGOPA-1471 adding cbill field in ec pages

---

src/components/Sidebar.tsx

Changing api-cfg cache configuration id to time
Necessary in order to gather useful and readable informations about the cache configuration used in a certain moment
Manually

PAGOPA-1790 changing cache config id to time

---

package.json
src/pages/channels/ChannelView.tsx
src/pages/channels/CreateChannel.tsx
src/pages/stations/CreateStation.tsx
src/pages/stations/StationView.tsx

Adding flag_standin configuration to channel and station pages
Needed in order to properly manage the new field
Manually
Canale:
Stazione:

PAGOPA-1622 adding value in station and channel pages

---

src/pages/creditorInstitutions/CreditorInstitution.tsx
src/pages/creditorInstitutions/EditCreditorInstitution.tsx
src/pages/stations/Station.tsx

Adding flag "pagamento spontaneo" in stations and ecs pages
Needed in order to change the values from fe
Manually

Main 13 flag pagamento spontaneo

---

src/pages/paymentServiceProviders/CreatePaymentServiceProvider.tsx
src/pages/paymentServiceProviders/EditPaymentServiceProvider.tsx
src/pages/paymentServiceProviders/PaymentServiceProvider.tsx

- add vat_number field to PSP create, edit and view pages
This change was needed to have the apiconfig front end aligned with the db records, where the vat_number column and value were already present.
- Tested locally starting the apiconfig back end and front end services and created, edited and viewed the VAT number for a PSP record
- NOTE: the already existing PSP entries which don't have the vat_number populated will show the value as null in the database.
The demo video is done on a local instance of the service using a mock H2 database
https://github.com/user-attachments/assets/729ff340-9c32-466a-b2ed-86ecf1c48fbb

[PIDM-263] fix: missing PSP vat_number field
